### ISSUE TITLE
Add dependabot.yml

### ISSUE THREAD

**Issue by BernhardMaier** [BernhardMaier/variableChecker#27]
Path:
```
.github/dependabot.yml
```

Content:
```
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```
